[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.alacritty]
input_path = './templates/alacritty-colors.css'
output_path = '~/.config/alacritty/alacritty-colors.toml'

[templates.hyprland]
input_path = './templates/hyprland.colors.css'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/waybar-colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.hyprlock]
input_path = './templates/hyprlock-colors.css'
output_path = '~/.config/hypr/hyprlock-colors.conf'


[templates.wofi]
input_path = './templates/wofi-colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.swaync]
input_path = './templates/swaync-colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
