~/.config/hypr/
~/.config/fastfetch/
~/.config/nvim/
~/.config/kitty/
~/.config/rofi/
~/.config/mako/
~/.config/fastfetch/
~/.config/wlogout/
~/.config/quickshell/
~/.config/mpd/
~/.config/Code/User/settings.json
~/Pictures/Wallpapers/
~/.zshrc
