~/.config/hypr/
~/.config/fastfetch/
~/.config/nvim/
~/.config/kitty/
~/.config/rofi/
~/.config/mpd/
~/.config/quickshell/
~/.config/Code/User/settings.json
~/.config/zed/
~/.config/scripts/
~/.config/kdeglobals
~/.config/opencode/
~/.config/pipewire/pipewire.conf.d/
~/.config/mimeapps.list
~/.config/matugen/
~/.config/gtk-3.0/
~/.config/gtk-4.0/
~/.config/fish/
~/Pictures/Wallpapers/

~/.config/bspwm/
~/.config/sxhkd/
~/.config/picom/
