~/.config/hypr/
~/.config/fastfetch/
~/.config/nvim/
~/.config/kitty/
~/.config/rofi/
~/.config/fastfetch/
~/.config/mpd/
~/.config/dunst/
~/.config/quickshell/
~/.config/Code/User/settings.json
~/.config/kdeglobals
~/Pictures/Wallpapers/
~/.zshrc

~/.config/bspwm/
~/config/sxhkd/
~/.config/picom/
