# --- Main Colors ---
background            #12140e
foreground            #e2e3d8
cursor                #e2e3d8
cursor_text_color     #12140e

selection_background  #414a33
selection_foreground  #dce7c7

url_color             #a0d0cb

# --- ANSI Colors ---
color0                #12140e
color1                #ffb4ab
color2                #a0d0cb
color3                #c0cbac
color4                #b3d088
color5                #a0d0cb
color6                #c0cbac
color7                #e2e3d8

color8                #44483d
color9                #93000a
color10               #1f4e4b
color11               #414a33
color12               #364e14
color13               #414a33
color14               #1f4e4b
color15               #c5c8b9

# --- Starship Prompt Bubbles ---
color255              #364e14
color254              #b3d088
color253              #414a33
color252              #c0cbac
color251              #1f4e4b
color250              #a0d0cb
color249              #93000a
color248              #ffb4ab

color232              #ceeda2
color233              #203600
color234              #dce7c7
color235              #2a331e
color236              #bcece7
color237              #003734
color238              #ffdad6
color239              #690005
color240              #ceeda2

# Matched with unthemed light/dark
color243              #b3d088
color244              #ffb4ab
color245              #44483d

# --- UI Elements ---
active_tab_foreground   #203600
active_tab_background   #b3d088
inactive_tab_foreground #ceeda2
inactive_tab_background #364e14

active_border_color     #b3d088
inactive_border_color   #8f9285

# --- Marks ---
mark1_foreground        #112000
mark1_background        #ceeda2
mark2_foreground        #161e0b
mark2_background        #dce7c7
mark3_foreground        #00201e
mark3_background        #bcece7
