# --- Main Colors ---
background            #18120c
foreground            #ede0d4
cursor                #ede0d4
cursor_text_color     #18120c

selection_background  #57432b
selection_foreground  #fbdebc

url_color             #bacd9f

# --- ANSI Colors ---
color0                #18120c
color1                #ffb4ab
color2                #bacd9f
color3                #dec2a2
color4                #f6bc70
color5                #bacd9f
color6                #dec2a2
color7                #ede0d4

color8                #4f4539
color9                #93000a
color10               #3b4c29
color11               #57432b
color12               #643f00
color13               #57432b
color14               #3b4c29
color15               #d3c4b4

# --- Starship Prompt Bubbles ---
color255              #643f00
color254              #f6bc70
color253              #57432b
color252              #dec2a2
color251              #3b4c29
color250              #bacd9f
color249              #93000a
color248              #ffb4ab

color232              #ffddb6
color233              #462b00
color234              #fbdebc
color235              #3e2d16
color236              #d5e9ba
color237              #263514
color238              #ffdad6
color239              #690005
color240              #ffddb6

# Matched with unthemed light/dark
color243              #f6bc70
color244              #ffb4ab
color245              #4f4539

# --- UI Elements ---
active_tab_foreground   #462b00
active_tab_background   #f6bc70
inactive_tab_foreground #ffddb6
inactive_tab_background #643f00

active_border_color     #f6bc70
inactive_border_color   #9c8e80

# --- Marks ---
mark1_foreground        #2a1800
mark1_background        #ffddb6
mark2_foreground        #271905
mark2_background        #fbdebc
mark3_foreground        #111f03
mark3_background        #d5e9ba
