confirm_os_window_close 0
font_family JetBrainsMonoNerdFont

background              #13151A
foreground              #d4c5b0
selection_background    #A08EC4
selection_foreground    #13151A
cursor                  #A08EC4
cursor_text_color       #13151A
url_color               #7EA3CC

color0   #13151A
color1   #C47A7A
color2   #7EBD9B
color3   #e6c97a
color4   #7EA3CC
color5   #A08EC4
color6   #7EBD9B
color7   #d4c5b0

color8   #2A2D35
color9   #C47A7A
color10  #7EBD9B
color11  #f0d898
color12  #7EA3CC
color13  #A08EC4
color14  #7EBD9B
color15  #F0F1F5
