background          = 0xFF13151A
base                = 0xFF1A1D24
alternate_base      = 0xFF2A2D35

text                = 0xFFd4c5b0
bright_text         = 0xFFF0F1F5

accent              = 0xFFA08EC4
accent_secondary    = 0xFF7EA3CC

font_family_monospace = JetBrainsMono Nerd Font