background {
    monitor =
    path = /home/ely/Pictures/Wallpapers/.current-wallpaper.png
    blur_size = 5
    blur_passes = 3
    brightness = 0.55
}

input-field {
    monitor =
    size = 6%, 4%
    outline_thickness = 0
    dots_rounding = 4
    dots_spacing = 0.5
    inner_color = rgba(47, 56, 62, 0.75)
    outer_color = rgba(47, 56, 62, 0.75)
    check_color = rgba(167, 192, 128, 1.0)
    fail_color = rgba(231, 138, 78, 1.0)
    font_color = rgba(211, 198, 170, 1.0)
    font_family = JetBrains Mono Nerd Font
    fade_on_empty = false
    shadow_color = rgba(0, 0, 0, 0.5)
    shadow_passes = 2
    shadow_size = 2
    rounding = 20
    placeholder_text = <i></i>
    fail_text = <b>FAIL</b>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"<b>%H</b>"
    color = rgba(167, 192, 128, 1.0)
    font_size = 200
    font_family = JetBrains Mono Nerd Font
    shadow_passes = 0
    shadow_size = 5
    position = -120, 410
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"<b>%M</b>"
    color = rgba(131, 192, 146, 0.4)
    font_size = 200
    font_family = JetBrains Mono Nerd Font
    shadow_passes = 0
    shadow_size = 5
    position = 120, 230
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"<b>%A, %B %d, %Y</b>"
    color = rgba(211, 198, 170, 1.0)
    font_size = 40
    font_family = JetBrains Mono Nerd Font
    shadow_passes = 0
    shadow_size = 4
    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi there! $USER
    color = rgba(211, 198, 170, 1.0)
    font_size = 24
    font_family = JetBrains Mono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
