general {
    lock_cmd = pidof hyprlock || hyprlock
}
listener {
    timeout = 1200
    on-timeout = notify-send "System" "You are about to be locked out!"
}

listener {
    timeout = 2400
    on-timeout = loginctl lock-session
    on-resume = sleep 2 && notify-send "System" "Unlocked! Hey $USER"
}

