background          = 0xFF181616   # dragonBlack0
base                = 0xFF1d1c19   # dragonBlack3
alternate_base      = 0xFF2d4f67   # dragonBlue surface

text                = 0xFFC5C9C5   # dragonWhite
bright_text         = 0xFFC5C9C5   # dragonWhite

accent              = 0xFF8BA4B0   # dragonBlue
accent_secondary    = 0xFF8EA4A2   # dragonTeal

font_family_monospace = JetBrainsMono Nerd Font