# --- Main Colors ---
background            #181115
foreground            #eddfe3
cursor                #eddfe3
cursor_text_color     #181115

selection_background  #58404c
selection_foreground  #fcd9e9

url_color             #f3ba9c

# --- ANSI Colors ---
color0                #181115
color1                #ffb4ab
color2                #f3ba9c
color3                #dfbecc
color4                #fbb0d7
color5                #f3ba9c
color6                #dfbecc
color7                #eddfe3

color8                #504349
color9                #93000a
color10               #643d26
color11               #58404c
color12               #6c3454
color13               #58404c
color14               #643d26
color15               #d4c2c8

# --- Starship Prompt Bubbles ---
color255              #6c3454
color254              #fbb0d7
color253              #58404c
color252              #dfbecc
color251              #643d26
color250              #f3ba9c
color249              #93000a
color248              #ffb4ab

color232              #ffd8ea
color233              #511d3d
color234              #fcd9e9
color235              #402a35
color236              #ffdbc9
color237              #4a2712
color238              #ffdad6
color239              #690005
color240              #ffd8ea

# Matched with unthemed light/dark
color243              #fbb0d7
color244              #ffb4ab
color245              #504349

# --- UI Elements ---
active_tab_foreground   #511d3d
active_tab_background   #fbb0d7
inactive_tab_foreground #ffd8ea
inactive_tab_background #6c3454

active_border_color     #fbb0d7
inactive_border_color   #9c8d93

# --- Marks ---
mark1_foreground        #380727
mark1_background        #ffd8ea
mark2_foreground        #291520
mark2_background        #fcd9e9
mark3_foreground        #311302
mark3_background        #ffdbc9
