# --- Main Colors ---
background            #11140f
foreground            #e0e4da
cursor                #e0e4da
cursor_text_color     #11140f

selection_background  #3c4b37
selection_foreground  #d6e8cd

url_color             #a0cfd3

# --- ANSI Colors ---
color0                #11140f
color1                #ffb4ab
color2                #a0cfd3
color3                #baccb2
color4                #a3d397
color5                #a0cfd3
color6                #baccb2
color7                #e0e4da

color8                #42493f
color9                #93000a
color10               #1e4d51
color11               #3c4b37
color12               #265022
color13               #3c4b37
color14               #1e4d51
color15               #c2c8bc

# --- Starship Prompt Bubbles ---
color255              #265022
color254              #a3d397
color253              #3c4b37
color252              #baccb2
color251              #1e4d51
color250              #a0cfd3
color249              #93000a
color248              #ffb4ab

color232              #bef0b1
color233              #0e380d
color234              #d6e8cd
color235              #263422
color236              #bcebef
color237              #00363a
color238              #ffdad6
color239              #690005
color240              #bef0b1

# Matched with unthemed light/dark
color243              #a3d397
color244              #ffb4ab
color245              #42493f

# --- UI Elements ---
active_tab_foreground   #0e380d
active_tab_background   #a3d397
inactive_tab_foreground #bef0b1
inactive_tab_background #265022

active_border_color     #a3d397
inactive_border_color   #8c9388

# --- Marks ---
mark1_foreground        #002202
mark1_background        #bef0b1
mark2_foreground        #111f0f
mark2_background        #d6e8cd
mark3_foreground        #002022
mark3_background        #bcebef
