#################
### AUTOSTART ###
#################

# Panel / system tray / notifications
exec-once = qs
exec-once = nm-applet
exec-once = blueman-applet
exec-once = mako

# Hyprland ecosystem
exec-once = hyprsunset
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent

# Apps / services
exec-once = awww-daemon
# exec-once = vesktop --start-minimized
# exec-once = discord --start-minimized
# exec-once = steam -silent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = cliphist wipe
exec-once = udiskie
exec-once = easyeffects --gapplication-service
exec-once = xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
exec-once = gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty