#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant = altgr-intl

    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    touchpad {
        natural_scroll = true
    }
}

device {
  name = at-translated-set-2-keyboard
  kb_layout = br
  kb_variant = abnt2
}

device {
  name = crq1080:00-0488:1014-touchpad
  sensitivity = 0
  accel_profile = adaptive
  disable_while_typing = true
}

device {
    name = logitech-wireless-receiver-mouse
    sensitivity = 0
    accel_profile = flat
    natural_scroll = false
  }