##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests
# windowrule {
#   name = windowrule-1
#   suppress_event = maximize
#   match:class = .*
# }


# Fix XWayland dragging issues
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


# Workspace 4 uses master layout
workspace = 4, layout:master

# Discord / Vesktop / Telegram → workspace 4
windowrule {
  name = socials
  workspace = 4
  match:class = ^(vesktop|discord|org\.telegram\.desktop)$
}

# Youtube Music → workspace 5
windowrule {
  name = music
  workspace = 5
  match:class = ^(com\.github\.th_ch\.youtube_music)$
}


# Steam → workspace 9
windowrule {
  name = windowrule-7
  workspace = 9
  match:class = ^(steam)$
}


# Steam games (steam_app_123456) → workspace 10 fullscreen no border
windowrule {
  name = games
  workspace = 10
  fullscreen = on
  border_size = 0
  render_unfocused = on
  match:class = ^(steam_app_[0-9]+|dota2|cs2|lutris|heroic|gamescope|bg3)$
}

windowrule {
  name = gaming_workspace
  match:workspace = 10
  rounding = 0
  opacity = 1
  no_blur = true
  no_anim = true
  opaque = true
  no_shadow = true
  decorate = off
}

workspace = 10, gapsin:0, gapsout:0

# Blur waybar
layerrule {
  name = layerrule-1
  blur = on
  match:namespace = namespace:waybar
}

windowrule {
	name = fixintellij
	match:class = jetbrains-idea
	no_initial_focus = on
}
