context.modules = [
    {
        name = libpipewire-module-filter-chain
        args = {
            node.description = "RNNoise Microphone"
            media.name = "RNNoise Microphone"

            filter.graph = {
                nodes = [
                    {
                        type = ladspa
                        name = rnnoise
                        plugin = /usr/lib/ladspa/librnnoise_ladspa.so
                        label = noise_suppressor_mono
                        control = {
                            "VAD Threshold (%)" = 50
                            "VAD Grace Period (ms)" = 500
                            "Retroactive VAD Grace (ms)" = 100
                            "Placeholder" = 0
                            "Dry Mix" = 0
                        }
                    }
                ]
            }

            capture.props = {
                node.name = "rnnoise_input"
                node.description = "RNNoise Microphone Input"
                audio.channels = 1
                audio.position = [ MONO ]
            }

            playback.props = {
                node.name = "rnnoise_output"
                node.description = "RNNoise Microphone"
                media.class = "Audio/Source"
                audio.channels = 1
                audio.position = [ MONO ]
                node.passive = true
            }
        }
    }
]
